#!/bin/bash
#
# List remote Git branches and the last commit date for each branch. Sort by most recent commit date.
#
# Author: https://gist.github.com/jasonrudolph/1810768#gistcomment-1830434
#

git for-each-ref --sort=committerdate refs/heads/ --format='%(HEAD) %(color:red)%(objectname:short)%(color:reset);%(color:yellow)%(refname:short)%(color:reset);(%(color:green)%(committerdate:relative)%(color:reset));%(authorname);%(contents:subject)' | column -t -s ';'
